# Site settings
title: Find your balcony on the map!
email: balconsche@gmail.com
url: https://balcons.github.io
description: "This is my personal website where I publish my works."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: a1d5ff
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Maryna Chervinska @itmaryna
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/itmaryna
  - title: facebook
    url: https://www.facebook.com/marina.dollarbill
  - title: behance
    url: http://behance.com/itmaryna
  - title: github
    url: http://github.com/itmaryna

# Postal address (add as many lines as necessary)
address:
  - line: Barcelona, Spain

# Credits content
credits: '@vitovalov & Jerome Lachaud'

# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jekyll-sitemap
